export const metadata = {
  title: 'My Learning Journey',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p className="text-2xl font-bold bg-red-200 text-white">Header</p>
        </header>
        {children}
        <footer>
          <p className="text-2xl font-bold">Footer</p>
        </footer>
        </body>
    </html>
  )
}
